require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Job"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Refresh"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Supply"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Buildings"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Character"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Faction"
require "DT/UI/ZedColonies/MainWindow/MainWindowActions/DT_MainWindowActions_Help"
