-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Furniture.Bed] [Rarity.Common] (4 items)
    { item="Base.Mattress", basePrice=62, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Mov_FlatCoffin", basePrice=65, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeFuton", basePrice=65, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_UprightCoffin", basePrice=65, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Bench] [Rarity.Common] (2 items)
    { item="Base.Mov_BacklessWoodenBench", basePrice=42, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakBench", basePrice=42, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Chair] [Rarity.Common] (30 items)
    { item="Base.Mov_BeachChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueComfyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BluePlasticChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueRattanChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownComfyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkBlueChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkWoodenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DrumStool", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyBlackChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyWhiteChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FoldingChair", basePrice=13, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=1, max=15} },
    { item="Base.Mov_GreenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenComfyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyComfyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalStool", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OfficeChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeModernChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PileOCrepeChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleRattanChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedWoodenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteComfyChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenStool", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_YellowModernChair", basePrice=44, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Counter] [Rarity.Common] (23 items)
    { item="Base.Mov_BirchCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MobileCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrailerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCounter", basePrice=44, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Common] (88 items)
    { item="Base.Antlers_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Bull_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Cow_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerStag_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Mov_BeigeCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=66, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagAdmin", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSA", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSALarge", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayLongCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp1", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp2", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp3", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp4", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp5", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp6", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorLarge", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmallWide", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorTall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorWood", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=66, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_NeonOpenSign", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=66, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAaaaah", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAbeLincoln", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAppleFacedMan", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBejaminFranklin", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBetty", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingCalvinist", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingChromaticAccident", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingDesertLandscape", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingElisa", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGeorgeWashington", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGreen", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingHelianthus", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingIslandBeach", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingJohnAdams", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLakeside", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLibrary", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLillysWaterpond", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingManWithOneEar", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMargarite", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMountNeverRest", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNightWithStars", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNomadAboveTheGloom", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingRiverside", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingShesGotIt", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingSirBrakefire", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingThomasJefferson", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingTwoFrame", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingVioletta", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PinkCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterDroids", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterElement", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterMedical", basePrice=41, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_PosterOmega", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPaws", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieBlue", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieGreen", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPiePink", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieRed", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=66, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SaleSign", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignCitrus", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Fossoil", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Gas2Go", basePrice=46, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignRestricted", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignWarning", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SquareWallClock", basePrice=47, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_StopSign", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WallClock", basePrice=47, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCurtain", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Pig_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Sheep_Skull_Wall", basePrice=37, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Rare] (1 item)
    { item="Base.Frame", basePrice=62, tags={"Building.Furniture.Decor", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },

    -- [Building.Furniture.Decor] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_SignArmy", basePrice=81, tags={"Building.Furniture.Decor", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.General] [Rarity.Common] (1 item)
    { item="Base.MetalDrum", basePrice=38, tags={"Building.Furniture.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Common] (17 items)
    { item="Base.Mov_BirchDrawers", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=50, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackSpeakerCabinet", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_CabinetMedical", basePrice=54, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_CabinetTool", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FirstAidCabinet", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Mailbox", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalWallShelves", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakShelves", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PublicMailBox", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPineCabinet", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=56, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=14} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodSpeakerCabinet", basePrice=48, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_MilitaryCrate", basePrice=96, tags={"Building.Furniture.Storage", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.Table] [Rarity.Common] (12 items)
    { item="Base.Mov_BlackLowModernTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownLowTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyDarkTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyLowTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LightRoundTable", basePrice=48, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakRoundTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingFlowersOnTable", basePrice=44, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticLowTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallTable", basePrice=42, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
})

print("[DynamicTrading] Furniture Registry Complete")
