-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Garden] [Rarity.Common] (11 items)
    { item="Base.Mov_BonsaiTree", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_BrickPlanter", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Cactus", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_CastIronPlant", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_ChineseEvergreen", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_DragonTree", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Fern", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Ficus", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_RaisedPlantbed", basePrice=55, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_SnakePlant", basePrice=45, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Mov_VioletFlowers", basePrice=43, tags={"Building.Garden", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=4} },

    -- [Building.Garden] [Rarity.Rare] (12 items)
    { item="Base.AnimalFeedBag", basePrice=89, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.CompostBag", basePrice=100, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Fertilizer", basePrice=101, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.GardeningSprayAphids", basePrice=103, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayCigarettes", basePrice=103, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayEmpty", basePrice=30, tags={"Building.Garden", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.GardeningSprayMilk", basePrice=103, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.GrassBag", basePrice=90, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.HerbivoreTeeth", basePrice=77, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.SlugRepellent", basePrice=103, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.SunflowerHead", basePrice=77, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.SunflowerHeadDried", basePrice=77, tags={"Building.Garden", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },

    -- [Building.Garden.Seed] [Rarity.Rare] (100 items)
    { item="Base.BarleyBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BasilBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BasilSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.BellPepperBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BellPepperSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.BlackSageBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BlackSageSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.BroadleafPlantainBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BroadleafPlantainSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.BroccoliBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.BroccoliSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CabbageBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CabbageSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CarrotBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CarrotSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CauliflowerBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CauliflowerSeed", basePrice=120, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.ChamomileBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ChamomileSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.ChivesBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ChivesSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CilantroBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ComfreyBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ComfreySeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CommonMallowBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CommonMallowSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.CornBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CornBagSeed_Empty", basePrice=35, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=52} },
    { item="Base.CucumberBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.CucumberSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.FlaxBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.GarlicBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.GarlicSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.GreenpeasBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.HabaneroBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.HabaneroSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.HempBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.HempSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.HopsBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.HopsSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.JalapenoBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.JalapenoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.KaleBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.KaleSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.LavenderBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.LavenderSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.LeekBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.LeekSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.LemonGrassBagSeed", basePrice=126, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.LemonGrassSeed", basePrice=126, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=30} },
    { item="Base.LettuceBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.LettuceSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.MarigoldBagSeed", basePrice=35, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=26} },
    { item="Base.MarigoldSeed", basePrice=35, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=52} },
    { item="Base.MintBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.MintSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.OnionBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.OnionSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.OreganoBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.OreganoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.ParsleyBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ParsleySeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.PoppyBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.PotatoBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.PotatoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.PumpkinBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.RedRadishBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.RedRadishSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.RoseBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.RosemaryBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.RosemarySeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.RoseSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.RyeBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SageBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SageSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.SoybeansBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SpinachBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SpinachSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.StrewberrieBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.StrewberrieSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.SugarBeetBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SugarBeetSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.SunflowerBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SweetPotatoBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.SweetPotatoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.ThymeBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ThymeSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.TobaccoBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.TobaccoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.TomatoBagSeed2", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.TomatoSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.TurnipBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.TurnipSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.WatermelonBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.WatermelonSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.WheatBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.WildGarlicBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.WildGarlicSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
    { item="Base.ZucchiniBagSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=22} },
    { item="Base.ZucchiniSeed", basePrice=117, tags={"Building.Garden.Seed", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=44} },
})

print("[DynamicTrading] Garden Registry Complete")
