-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Moveable] [Rarity.Common] (92 items)
    { item="Base.Mov_AirConditioner", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine1", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine2", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BenchGrinder", basePrice=68, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BinRound", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Birdbath", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackBBQ", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackCashRegister", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Brazier", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CardboardBox", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CashRegister", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ClothesStand", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CoffeeMaker", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteMixer", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteRoadBlock", basePrice=56, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CorkBoard", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Cot", basePrice=57, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Mov_DarkGreenBarrel", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DeepFryer", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DegreeDoctor", basePrice=55, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DegreeSurgeon", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DesktopComputer", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Doghouse", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Espresso", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ExtractorHood", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FireHydrant", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FitnessContraption", basePrice=57, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=20} },
    { item="Base.Mov_GardenGnome", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveArched", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveRound", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveSquare", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveWorn", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GrayGarbageBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GreenGarbageBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GuitarAmplifier", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Gurney", basePrice=44, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Mov_GymnMat", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HaystackDouble", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HaystackSingle", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HotdogMachine", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HuntingTrophy", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Jukebox", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KeyDuplicator", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KickDrum", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LargeOpenToppedGarbageBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightConstruction", basePrice=70, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightGreenBarrel", basePrice=55, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinFemale", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinMale", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MapUSA", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MetalTurnstile", basePrice=64, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microphone", basePrice=56, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microscope", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MobileBloodbag", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_OrangeBarrel", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletBricks", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletEmpty", basePrice=15, tags={"Building.Moveable", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=2, max=21} },
    { item="Base.Mov_PinballMachine", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo2", basePrice=47, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PopcornMachine", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Projector", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PublicGarbageBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RecycleBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RedBBQ", basePrice=66, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadBarrier", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone2", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SaltLick", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SatelliteDish", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ScaleMedical", basePrice=55, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Scarecrow", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal2", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityWallMonitors", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ShoppingBaskets", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SkeletonDisplay", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SmallChest", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SnareDrum", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_StandingVault", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TomDrum", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TVCamera", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WashingBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WheelieBin", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowChrome", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowSlider", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowTiled", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhite", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhiteTiled", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWooden", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WoodPegboard", basePrice=49, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
})

print("[DynamicTrading] Moveable Registry Complete")
